language: node_js
node_js: node
cache: yarn
jobs:
  include:
  - stage: Test
    env: TEST_ENV=source
    before_script:
    # react-router CJS build is imported by react-router-config tests,
    # so we need to build it before running react-router-config tests
    - cd packages/react-router && BUILD_ENV=cjs yarn build && cd -
    script: yarn test
  - env: TEST_ENV=cjs BUILD_ENV=cjs
    before_script: yarn build
    script: yarn test
  - env: TEST_ENV=umd BUILD_ENV=umd
    before_script:
    # react-router ESM build is imported by react-router-dom UMD,
    # so we need to build it before building react-router-dom UMD
    - cd packages/react-router && BUILD_ENV=esm yarn build && cd -
    - yarn build
    # react-router CJS build is imported by react-router-config tests,
    # so we need to build it before running react-router-config tests
    - cd packages/react-router && BUILD_ENV=cjs yarn build && cd -
    script: yarn test
  - stage: Release
    if: tag =~ ^v[0-9]
    before_script: yarn build
    script: echo "Publishing $TRAVIS_TAG to npm ..."
    before_deploy: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
    deploy:
      provider: script
      skip_cleanup: true
      script: lerna publish from-git --yes --pre-dist-tag next
      on:
        tags: true
  - stage: Deploy Website
    if: branch = website-new
    env: PUBLIC_PATH=/react-router/
    before_script: yarn build
    script: echo "Deploying website to https://reacttraining.com$PUBLIC_PATH"
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_fbe3a224532e_key -iv $encrypted_fbe3a224532e_iv
      -in monorepo-deploy-key.enc -out monorepo-deploy-key -d
    - chmod 600 monorepo-deploy-key
    - eval $(ssh-agent -s)
    - ssh-add monorepo-deploy-key
    deploy:
      provider: script
      script: bash scripts/deploy-website-new.sh
      skip_cleanup: true
      on:
        branch: website-new
